name: Docker Image CI

on:  
 push:
    branches: [ "main" ]
 pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to the container registery
      uses: docker/login-action@v2
      with: 
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
  
    - name: Extract metadata for the Docker image
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ghcr.io/rsahin34/webserver

    - name: Build and Push docker Image
      uses: docker/build-push-action@v2
      with:
       context: .
       push: true
       #tags: |
       #   ghcr.io/rsahin34/webserver:latest
       tags: ${{ steps.meta.outputs.tags }}
       
  deploy:
     
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Kubernetes Set Context
       uses: Azure/k8s-set-context@v3.0
       with:
        kubeconfig: ${{secrets.KUBERNETES_SECRET}}

     - name: Extract metadata for the Docker image
       id: meta
       uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
       with:
        images: ghcr.io/rsahin34/webserver
       
     - name: Deploy to the Kubernetes cluster
       uses: Azure/k8s-deploy@v4
       with:
          namespace: rsahin
          manifests: first_deployment.yml
          images: ghcr.io/rsahin34/webserver/${{ steps.meta.outputs.tags }}
