name: Docker Image CI

on:  
 push:
    branches: [ "main" ]
 pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to the container registery
      uses: docker/login-action@v2
      with: 
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build and Push docker Image
      uses: docker/build-push-action@v2
      with:
       context: .
       push: true
       tags: |
         ghcr.io/rsahin34/webserver:latest
         ghcr.io/rsahin34/webserver:${{ github.sha }}
       
  deploy:
     
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Kubernetes Set Context
       uses: Azure/k8s-set-context@v3.0
       with:
        kubeconfig: ${{secrets.KUBERNETES_SECRET}}
       
     - name: Deploy to the Kubernetes cluster
       uses: Azure/k8s-deploy@v4
       with:
          namespace: rsahin
          manifests: first_deployment.yml
          force: true
          images: ghcr.io/rsahin34/webserver/:${{ github.sha }}
